name: theZoneApp
description: Pocket chrono-crafter!
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.8.0"
dependencies:
  provider: ^6.1.4
  syncfusion_flutter_calendar: ^28.2.11
  table_calendar: ^3.2.0
  flutter:
    sdk: flutter
flutter:
  uses-material-design: true
